### ISSUE TITLE
You can add free RP by going to the bot's DMs

### ISSUE THREAD

**Issue by winwastaken** [Shockshwat/support-bot#1]
You can add yourself RP by going to the bot's DMs and running /rp_add.

**To Reproduce**
1. Go to the bot's DMs
2. Send the /rp_add command
3. Check RP in WSC
4. Realize i got the RP

**Comment by Shockshwat** [comment]
Fixed with [0f1f169](https://github.com/Shockshwat/support-bot/commit/0f1f1693939651b71c74eef764d8a2c6f20535ba).
